// 25 snappy facts for first 25 refills, then 15 deeper-impact facts cycling after 25
export const refillFacts: string[] = [
  "Congrats! You just saved about 10 grams of plastic—like ditching 2 shopping bags!",
  "Refill win! You avoided around 80g of carbon—the same as driving 0.5 km less!",
  "Nice! One less bottle means thousands fewer microplastic bits polluting the ocean!",
  "You’ve prevented plastic equivalent to 20 straws from entering nature!",
  "Each refill helps protect marine animals—one bottle can seriously harm a turtle!",
  "Boom! You've saved around 3 liters of water used in bottle production!",
  "Each refill cuts enough CO₂ to charge your phone 10 times!",
  "Less plastic means happier seabirds—1 million birds die from plastic yearly!",
  "Awesome—today's refill cuts microplastic risk in Dubai’s precious coastline!",
  "You've prevented enough plastic to match the weight of 5 credit cards!",
  "Your refill avoided plastic equal to 3 takeaway coffee lids!",
  "Nice work! One refill cuts enough CO₂ to keep a LED bulb on all evening!",
  "Every refill means fewer bottles choking our marine wildlife!",
  "You just saved plastic equivalent to 5 single-use forks!",
  "Congrats! Your refill reduced carbon equal to skipping a short Uber ride!",
  "Each refill prevents plastic equivalent to a handful of bottle caps!",
  "Refilling protects Dubai’s shores—one fewer bottle reaching our beaches!",
  "You’ve avoided enough plastic to make 10 earbuds!",
  "Great refill! You’ve kept a bottle’s worth of microplastics out of the air and sea!",
  "You prevented the CO₂ of boiling a kettle twice—just by refilling!",
  "Less plastic means fewer toxins for marine life around Dubai’s coastline!",
  "Each refill reduces plastic equal to a disposable toothbrush!",
  "Nice refill—cutting plastic helps keep ocean habitats thriving!",
  "Great! You avoided enough plastic to make a small toy!",
  "Refill champion! You’ve just saved resources equal to filling your bottle 6 times!",
  // Deeper impact facts for 26+
  "Amazing! 30 refills save CO₂ equal to a drive from Dubai Marina to Downtown!",
  "35 refills = enough plastic saved to equal the weight of 70 plastic bags!",
  "40 refills avoided as many microplastics as found in a baby sea turtle's stomach!",
  "45 refills keep enough plastic from oceans to significantly protect sea life!",
  "50 refills! You saved plastic equal to a large beach cleanup bag!",
  "55 refills = carbon savings of a one-way car trip Dubai–Abu Dhabi!",
  "60 refills! You've prevented enough plastic to equal 250 straws!",
  "65 refills = microplastic pollution of hundreds of thousands fewer particles!",
  "70 refills = You’ve saved the water equivalent of filling a bathtub 3 times!",
  "75 refills! That’s enough plastic avoided to fill a soccer ball!",
  "80 refills prevent carbon emissions like skipping two Dubai–Sharjah drives!",
  "85 refills have kept millions of microplastics out of our waters!",
  "90 refills equal plastic savings of 1 kilogram—like ditching 180 grocery bags!",
  "95 refills = as much carbon saved as driving Dubai-Abu Dhabi roundtrip!",
  "100 refills—You’ve personally prevented billions of microplastic fragments!"
];
